spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: 12

test:
  test: blabla

#spring.data.jpa.repositories.bootstrap-mode=default
