eureka:
  client:
    service-url:
      defaultZone: ${SPRING_CLOUD_DISCOVERY_URI:http://localhost:8010}/eureka
server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
