server:
  port: ${PORT:0}
spring:
  application:
    name: task-ws
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8012}/config/
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
      name: task-ws
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: ${SPRING_CLOUD_DISCOVERY_URI:http://localhost:8010}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org:
      hibernate:
        sql: trace
        type: trace