server:
#  port: ${PORT:0}
spring:
  application:
    name: task-ws
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8012}/config/
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
      name: task-ws
      fail-fast: true
      retry:
        max-attempts: 20
        initial-interval: 2000
        max-interval: 5000
  jpa:
    show-sql: true
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: ${SPRING_CLOUD_DISCOVERY_URI:http://localhost:8010}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org:
      hibernate:
        sql: trace
        type: trace
resilience4j:
  retry:
    instances:
      sample:
        maxRetryAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
  circuitbreaker:
    instances:
      sample2:
        failureRateThreshold: 90
