server:
  port: 8083
spring:
  application:
    name: task-ws
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8012}/config/
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
      name: task-ws