eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true
#  server:
#    enable-self-preservation: false
server:
  port: 8010
spring:
  application:
    name: discovery-ws