eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
info:
  name: account-service
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
  port: ${PORT:0}
spring:
  application:
    name: account-ws
  messages:
    basename: messages


logging:
  level:
    com:
      dmi:
        linker:
          controller:
            UserController: trace
